baseURL: http://weishanhe.github.io
languageCode: en-us
title: Weishan He
theme: hugo-profile


Paginate: 3
googleAnalytics: G-KRWDYV9R15

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: projects
    #   name: Projects
    #   title: Projects
    #   url: /projects
    #   weight: 1
    
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    - identifier: resume
      name: Resume
      title: Resume
      url: /resume
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Weishan He"
  description: A data practitioner who develops machine-learning-based products to assist business in scaling
  # staticPath: ""  # The path to serve the static files from
  favicon: "/cup_fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, I am"
    title: "Weishan."
    # subtitle: "I am a results-oriented data scientist "
    content: "
    I am a machine learning practitioner with experience developing machine-learning-based products and directing experiments.
    <br> 
    <br>
    During the development and deployment of machine learning models, I used a variety of tools, including Python, SQL, Google Cloud Platform, Docker, Poetry, etc. 
    Currently, I am working at Andela as a Data Scientist to assist in the development of machine-learning features that will enable sustained growth in a dynamic marketplace.
    Please see *Projects* below for more interesting projects I conducted.
    <br>
    <br>
    The challenging process of transforming large amounts of raw data into intelligent tools makes me very excited. As part of my leisure time, I continue to develop my skill sets in order to achieve this goal.
    "
    
    
    image: /images/hero_image.jpg
    button:
      enable: true
      # name: "Projects"
      # url: "/projects"
      buttonList:
        - name: "Projects"
          url: "#projects"
        - name: "Resume"
          url: "/resume"
    
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/weishanhe/
        - icon: fab fa-github
          url: https://github.com/WeishanHe
        - icon: fab fa-twitter
          url: https://twitter.com/Weishan21497480
        - icon: fa fa-envelope
          url: mailto:weishanhe@hotmail.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  # about:
  #   enable: true
  #   title: "About Me"
  #   # image: "/images/me.png"
  #   content: |-
  #     I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

  #     I am currently working on a project that will be used to help people find the best way to get around the city.
  #   skills:
  #     enable: true
  #     title: "Here are a few technologies I've been working with recently:"
  #     items:
  #       - "HTML"
  #       - "CSS"
  #       - "JavaScript"
  #       - "React"
  #       - "Node"
  #       - "Express"

  # Experience
  # experience:
  #   enable: true
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  # education:
  #   enable: true
  #   # index: true
  #   items:
  #     - title: "Master of Business Administration"
  #       school:
  #         name: "University of California, Berkeley"
  #         url: "https://example.org"
  #       date: "2013 - 2015"
  #       GPA: "3.8 out of 5.0"
  #       content: |-
  #         Extracurricular Activities
  #           - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  #           - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
  #     - title: "Bachelor of Science in Computer Science"
  #       school:
  #         name: "Massachusetts Institute of Technology"
  #         url: "https://example.org"
  #       date: "2009 - 2013"
  #       GPA: "3.9 out of 5.0"
  #       content: |-
  #         I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
  #         - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
  #         - Face mask detection using a single convolutional neural network.

  #         Extracurricular Activities
  #           - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  #           - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
  #       featuredLink:
  #         enable: true
  #         name: "My academic record"
  #         url: "https://example.com"
  #     - title: "High School"
  #       school:
  #         name: "Thomas Jefferson High School for Science and Technology."
  #         url: "https://example.org"
  #       GPA: "4.2 out of 5.0"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Stock Price Prediction with LSTM
        content: Applied LSTM on time-series data to predict future stock price
        image: /images/projects/stock_price_prediction_lstm.jpg
        featured:
          name: Demo
          link: https://github.com/ruihao-li/machine-learning-compilation/tree/main/LSTM
        badges:
          - "LSTM"
          - "Time-Series"
          - "PyTorch"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/6.%20Diabetes%20Detection%20Using%20LR%26SVM%26RF%20(in%20Python)

      - title: Build Hotel Database Using Web Scrapping
        content: Leverage Selenium and BeautifulSoup to scrap hotel information from booking.com and convert the data into MongoDB collection to save them in a JSON file
        image: /images/projects/hotel_webscraping.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Web-Scraping/tree/master/1.%20Build%20Hotel%20Database%20Using%20Web%20Scrapping%20(in%20Python)
        badges:
          - "Web Scrapping"
          - "ETL"
          - "MongoDB"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Web-Scraping/tree/master/1.%20Build%20Hotel%20Database%20Using%20Web%20Scrapping%20(in%20Python)

      - title: New Feature Performance Evaluation using DiD and CLV
        content: Use diff-in-diff and logistic regression to evaluate the effectiveness of a new feature - online gaiming community - by measuring the change in user revenue and retention
        image: /images/projects/gaming_did_clv.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Data-Science-Projects/tree/main/1.%20New%20Feature%20Performance%20Evaluation%20using%20DID%20and%20CLV%20(in%20R)
        badges:
          - "DiD"
          - "CLV"
          - "R"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/1.%20New%20Feature%20Performance%20Evaluation%20using%20DID%20and%20CLV%20(in%20R)

      - title: New TV Design Using Conjoint Analysis
        content: Deploy conjoint analysis to generate a TV Design that will lead to the optimal market share
        image: /images/projects/TV_conjoint_analysis.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Data-Science-Projects/tree/main/2.%20New%20TV%20Design%20Using%20Conjoint%20Analysis%20(in%20R)
        badges:
          - "Conjoint Analysis"
          - "Pricing Analysis"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/2.%20New%20TV%20Design%20Using%20Conjoint%20Analysis%20(in%20R)

      - title: Superstore Sales Performance Dashboard
        content: Construct an interactive dashboard in Tableau to track sales performance for a supermarket
        image: /images/projects/supermarket_dashboard.jpg
        featured:
          name: Demo
          link: https://public.tableau.com/app/profile/weishan.he/viz/ReplicatedSupermarketSalesDashboard/Dashboard2
        badges:
          - "Data Visualization"
          - "Tableau"
          - "Dashboard"

      - title: Use Bootstrap to Obtain Confidence Levels for Willingness to Pay
        content: Apply Data Bootstrap and Residual Bootstrap to obtain the 95% confidence levels and median for willingness to pay
        image: /images/projects/bootstrap_wtp.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Data-Science-Projects/tree/main/3.%20Use%20Bootstrap%20to%20obtain%20Confidence%20Levels%20for%20Willingness%20to%20Pay%20(in%20R)
        badges:
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/3.%20Use%20Bootstrap%20to%20obtain%20Confidence%20Levels%20for%20Willingness%20to%20Pay%20(in%20R)

      - title: Use PCA and PCR to Visualize Brand Competition in Brand Map
        content: Build brand maps for car brands using principal component analysis and recommend strategies to focal brand's mangers to improve their product design
        image: /images/projects/car_brand_map.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Data-Science-Projects/tree/main/4.%20Brand%20Map_Use%20PCA%20and%20PCR%20to%20Visualize%20Brand%20Competition%20(in%20R)
        badges:
          - "PCA"
          - "PCR"
          - "Brand Map"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/4.%20Brand%20Map_Use%20PCA%20and%20PCR%20to%20Visualize%20Brand%20Competition%20(in%20R)
          
      - title: Fraud Detection Using Supervised Machine Learning
        content: Build ETL and apply logistic regression, random forest, and XGBoost to detect fraudulent activities
        image: /images/projects/fraud detection.jpg
        featured:
          name: Demo
          link: https://github.com/WeishanHe/Data-Science-Projects/tree/main/5.%20Fraud%20Detection%20Using%20Supervised%20Machine%20Learning%20(in%20Python)
        badges:
          - "Logistic Regression"
          - "Random Forest"
          - "XGBoost"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/WeishanHe/Data-Science-Projects/tree/main/5.%20Fraud%20Detection%20Using%20Supervised%20Machine%20Learning%20(in%20Python)


  #Contact
  # contact:
  #   enable: true
  #   content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
  #   email: gurusabarisha@gmail.com
  #   btnName: Mail me

  footer:
    recentPosts: false
  #   socialNetworks:
  #     github: https://github.com
  #     linkedin: https://linkedin.com
  #     twitter: https://twitter.com
  #     instagram: https://instagram.com
  #     facebook: https://facebook.com

